### ISSUE TITLE
Jcache check status error

### ISSUE THREAD

**Issue by IamShubhamGupto** [m2lines/L96_demo#80]
## Error
On following the README to check status of the cache
```
jcache cache list -p _build/.jupyter_cache
```
Did **NOT** run condo-lock command as it is designed for linux

### Output
```
(L96M2lines) shubham@Shubhams-MBP L96_demo % jcache cache list -p _build/.jupyter_cache
Cache path: _build/.jupyter_cache
The cache does not yet exist, do you want to create it? [y/N]: y
No Cached Notebooks
Traceback (most recent call last):
  File "/Users/shubham/opt/anaconda3/envs/L96M2lines/bin/jcache", line 10, in <module>
    sys.exit(jcache())
  File "/Users/shubham/opt/anaconda3/envs/L96M2lines/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/shubham/opt/anaconda3/envs/L96M2lines/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/shubham/opt/anaconda3/envs/L96M2lines/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/shubham/opt/anaconda3/envs/L96M2lines/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/shubham/opt/anaconda3/envs/L96M2lines/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/shubham/opt/anaconda3/envs/L96M2lines/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/shubham/opt/anaconda3/envs/L96M2lines/lib/python3.9/site-packages/jupyter_cache/cli/commands/cmd_cache.py", line 44, in list_caches
    tabulate_cache_records(records, hashkeys=hashkeys, path_length=path_length)
  File "/Users/shubham/opt/anaconda3/envs/L96M2lines/lib/python3.9/site-packages/jupyter_cache/utils.py", line 83, in tabulate_cache_records
    import tabulate
ModuleNotFoundError: No module named 'tabulate'
```

Device: Mac OS (M1)

## Fix
```conda install tabulate```
### Output:
```
(L96M2lines) shubham@Shubhams-MBP L96_demo % jcache cache list -p _build/.jupyter_cache
No Cached Notebooks

(L96M2lines) shubham@Shubhams-MBP L96_demo %
```

### Comment
update environment to include tabulate

**Comment by IamShubhamGupto** [comment]
Fix PR: https://github.com/m2lines/L96_demo/pull/81
